apiVersion: m.oneprovider.com/v1alpha1
kind: SshKey
metadata:
  name: hello-oneprovider
spec:
  forProvider:
    name: namespacedexample
    publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMbAn3/YgZhhmsQIiGjOPOhODxpKXUo+LF3rFBvOOnYw"
  providerConfigRef:
    name: default
    kind: ProviderConfig
