apiVersion: vm_instance.oneprovider.oneprovider.com/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: vm_instance/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: vm
  name: vm
spec:
  forProvider:
    hostname: theOneRing
    instanceSizeId: "45"
    locationId: ${data.oneprovider_vm_location.paris.id}
    templateId: ${data.oneprovider_vm_template.ubuntu.id}
