// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type InstanceInitParameters struct {

	// (String) Hostname of the VM instance
	// Hostname of the VM instance
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) Instance size ID referencing the hardware specs of the VM instance
	// Instance size ID referencing the hardware specs of the VM instance
	InstanceSizeID *string `json:"instanceSizeId,omitempty" tf:"instance_size_id,omitempty"`

	// (String) Location ID referencing where the VM instance will be created
	// Location ID referencing where the VM instance will be created
	LocationID *string `json:"locationId,omitempty" tf:"location_id,omitempty"`

	// (List of String) List of SSH keys UUID to add to the VM instance. Note: The OneProvider API does not return SSH key information, so the state reflects the configured values rather than the actual server state.
	// List of SSH keys UUID to add to the VM instance. Note: The OneProvider API does not return SSH key information, so the state reflects the configured values rather than the actual server state.
	// +crossplane:generate:reference:type=github.com/MadJlzz/provider-oneprovider/apis/namespaced/ssh_key/v1alpha1.Key
	SSHKeys []*string `json:"sshKeys,omitempty" tf:"ssh_keys,omitempty"`

	// References to Key in ssh_key to populate sshKeys.
	// +kubebuilder:validation:Optional
	SSHKeysRefs []v1.NamespacedReference `json:"sshKeysRefs,omitempty" tf:"-"`

	// Selector for a list of Key in ssh_key to populate sshKeys.
	// +kubebuilder:validation:Optional
	SSHKeysSelector *v1.NamespacedSelector `json:"sshKeysSelector,omitempty" tf:"-"`

	// (String) Template ID referencing the OS to use for that VM instance
	// Template ID referencing the OS to use for that VM instance
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`
}

type InstanceObservation struct {

	// (String) Hostname of the VM instance
	// Hostname of the VM instance
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) ID of the VM instance. Generated by the provider.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) IP address of the VM instance
	// IP address of the VM instance
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (String) Instance size ID referencing the hardware specs of the VM instance
	// Instance size ID referencing the hardware specs of the VM instance
	InstanceSizeID *string `json:"instanceSizeId,omitempty" tf:"instance_size_id,omitempty"`

	// (String) Location ID referencing where the VM instance will be created
	// Location ID referencing where the VM instance will be created
	LocationID *string `json:"locationId,omitempty" tf:"location_id,omitempty"`

	// (List of String) List of SSH keys UUID to add to the VM instance. Note: The OneProvider API does not return SSH key information, so the state reflects the configured values rather than the actual server state.
	// List of SSH keys UUID to add to the VM instance. Note: The OneProvider API does not return SSH key information, so the state reflects the configured values rather than the actual server state.
	SSHKeys []*string `json:"sshKeys,omitempty" tf:"ssh_keys,omitempty"`

	// (String) Template ID referencing the OS to use for that VM instance
	// Template ID referencing the OS to use for that VM instance
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`
}

type InstanceParameters struct {

	// (String) Hostname of the VM instance
	// Hostname of the VM instance
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) Instance size ID referencing the hardware specs of the VM instance
	// Instance size ID referencing the hardware specs of the VM instance
	// +kubebuilder:validation:Optional
	InstanceSizeID *string `json:"instanceSizeId,omitempty" tf:"instance_size_id,omitempty"`

	// (String) Location ID referencing where the VM instance will be created
	// Location ID referencing where the VM instance will be created
	// +kubebuilder:validation:Optional
	LocationID *string `json:"locationId,omitempty" tf:"location_id,omitempty"`

	// (List of String) List of SSH keys UUID to add to the VM instance. Note: The OneProvider API does not return SSH key information, so the state reflects the configured values rather than the actual server state.
	// List of SSH keys UUID to add to the VM instance. Note: The OneProvider API does not return SSH key information, so the state reflects the configured values rather than the actual server state.
	// +crossplane:generate:reference:type=github.com/MadJlzz/provider-oneprovider/apis/namespaced/ssh_key/v1alpha1.Key
	// +kubebuilder:validation:Optional
	SSHKeys []*string `json:"sshKeys,omitempty" tf:"ssh_keys,omitempty"`

	// References to Key in ssh_key to populate sshKeys.
	// +kubebuilder:validation:Optional
	SSHKeysRefs []v1.NamespacedReference `json:"sshKeysRefs,omitempty" tf:"-"`

	// Selector for a list of Key in ssh_key to populate sshKeys.
	// +kubebuilder:validation:Optional
	SSHKeysSelector *v1.NamespacedSelector `json:"sshKeysSelector,omitempty" tf:"-"`

	// (String) Template ID referencing the OS to use for that VM instance
	// Template ID referencing the OS to use for that VM instance
	// +kubebuilder:validation:Optional
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`
}

// InstanceSpec defines the desired state of Instance
type InstanceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceInitParameters `json:"initProvider,omitempty"`
}

// InstanceStatus defines the observed state of Instance.
type InstanceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Instance is the Schema for the Instances API. Create a new VM instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oneprovider}
type Instance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.hostname) || (has(self.initProvider) && has(self.initProvider.hostname))",message="spec.forProvider.hostname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.instanceSizeId) || (has(self.initProvider) && has(self.initProvider.instanceSizeId))",message="spec.forProvider.instanceSizeId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.locationId) || (has(self.initProvider) && has(self.initProvider.locationId))",message="spec.forProvider.locationId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.templateId) || (has(self.initProvider) && has(self.initProvider.templateId))",message="spec.forProvider.templateId is a required parameter"
	Spec   InstanceSpec   `json:"spec"`
	Status InstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceList contains a list of Instances
type InstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Instance `json:"items"`
}

// Repository type metadata.
var (
	Instance_Kind             = "Instance"
	Instance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Instance_Kind}.String()
	Instance_KindAPIVersion   = Instance_Kind + "." + CRDGroupVersion.String()
	Instance_GroupVersionKind = CRDGroupVersion.WithKind(Instance_Kind)
)

func init() {
	SchemeBuilder.Register(&Instance{}, &InstanceList{})
}
