name: MadJlzz/oneprovider
resources:
    oneprovider_ssh_key:
        subCategory: ""
        description: Create a new public SSH key
        name: oneprovider_ssh_key
        title: oneprovider_ssh_key Resource - oneprovider
        examples:
            - name: ubuntu
              manifest: |-
                {
                  "name": "example",
                  "public_key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMbAn3/YgZhhmsQIiGjOPOhODxpKXUo+LF3rFBvOOnYl"
                }
        argumentDocs:
            id: (String) UUID of the SSH key resource.
            name: (String) Name of the SSH key resource.
            public_key: (String) Public key value.
        importStatements: []
    oneprovider_vm_instance:
        subCategory: ""
        description: Create a new VM instance.
        name: oneprovider_vm_instance
        title: oneprovider_vm_instance Resource - oneprovider
        examples:
            - name: vm
              manifest: |-
                {
                  "hostname": "theOneRing",
                  "instance_size_id": "45",
                  "location_id": "${data.oneprovider_vm_location.paris.id}",
                  "template_id": "${data.oneprovider_vm_template.ubuntu.id}"
                }
              references:
                location_id: data.oneprovider_vm_location.paris.id
                template_id: data.oneprovider_vm_template.ubuntu.id
        argumentDocs:
            hostname: (String) Hostname of the VM instance
            id: (String) ID of the VM instance. Generated by the provider.
            instance_size_id: (String) Instance size ID referencing the hardware specs of the VM instance
            ip_address: (String) IP address of the VM instance
            location_id: (String) Location ID referencing where the VM instance will be created
            password: (String, Sensitive) Password of the root user
            ssh_keys: '(List of String) List of SSH keys UUID to add to the VM instance. Note: The OneProvider API does not return SSH key information, so the state reflects the configured values rather than the actual server state.'
            template_id: (String) Template ID referencing the OS to use for that VM instance
        importStatements: []
