apiVersion: oneprovider.com/v1alpha1
kind: SshKey
metadata:
  annotations:
    meta.upbound.io/example-id: oneprovider/v1alpha1/sshkey
  labels:
    testing.upbound.io/example-name: ubuntu
  name: ubuntu
spec:
  forProvider:
    name: example
    publicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMbAn3/YgZhhmsQIiGjOPOhODxpKXUo+LF3rFBvOOnYl
