apiVersion: sshkey.oneprovider.com/v1alpha1
kind: Key
metadata:
  name: hello-crossplane
spec:
  forProvider:
    name: example
    publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMbAn3/YgZhhmsQIiGjOPOhODxpKXUo+LF3rFBvOOnYl"
  providerConfigRef:
    name: default